apiVersion: apps/v1
kind: Deployment
metadata:
  name: doom
  labels:
    app: doom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doom
  template:
    metadata:
      labels:
        app: doom
    spec:
      containers:
        - name: doom
          image: b0nam/docker-doom
          ports:
            - containerPort: 8080
          env:
            - name: PASSWORD
              value: "doom"  # You can set a custom VNC password here
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
