apiVersion: v1
kind: Service
metadata:
  name: doom
spec:
  type: NodePort
  selector:
    app: doom
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # Access via http://<NodeIP>:30080
